"""Per-session SSH keypairs.

Keys are per *session*, not per group: stopping a session invalidates the key,
so a student who leaves the course loses access at the next stop without anyone
having to rotate anything.

Generated by shelling out to ssh-keygen, which every Linux box already has, so
the service carries no crypto dependency.
"""

import pathlib
import subprocess
import tempfile


def new_keypair(comment: str = "gpulease") -> tuple[str, str]:
    """Return (private_key_pem, public_key_line)."""
    with tempfile.TemporaryDirectory() as tmp:
        path = pathlib.Path(tmp) / "k"
        subprocess.run(
            ["ssh-keygen", "-t", "ed25519", "-N", "", "-q", "-C", comment, "-f", str(path)],
            check=True,
            capture_output=True,
        )
        return path.read_text(), path.with_suffix(".pub").read_text().strip()
